// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmBGOl60MMujiOEr0SbKHXXNR4dwxwIkE',
    appId: '1:1042384658326:web:c72e88f21e9da2af4407b7',
    messagingSenderId: '1042384658326',
    projectId: 'mylatestproject-50982',
    authDomain: 'mylatestproject-50982.firebaseapp.com',
    databaseURL: 'https://mylatestproject-50982-default-rtdb.firebaseio.com',
    storageBucket: 'mylatestproject-50982.appspot.com',
    measurementId: 'G-VMMDJCQNKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI3rHccDyeyJicGJ-VCeKVhoIVoGKbNec',
    appId: '1:1042384658326:android:c42d56acfb3653294407b7',
    messagingSenderId: '1042384658326',
    projectId: 'mylatestproject-50982',
    databaseURL: 'https://mylatestproject-50982-default-rtdb.firebaseio.com',
    storageBucket: 'mylatestproject-50982.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRAVMw7cKcqTIacPj_ipuhJvAL5UqUtak',
    appId: '1:1042384658326:ios:ab9fde7c05de65984407b7',
    messagingSenderId: '1042384658326',
    projectId: 'mylatestproject-50982',
    databaseURL: 'https://mylatestproject-50982-default-rtdb.firebaseio.com',
    storageBucket: 'mylatestproject-50982.appspot.com',
    iosBundleId: 'com.example.violet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRAVMw7cKcqTIacPj_ipuhJvAL5UqUtak',
    appId: '1:1042384658326:ios:3ba5ce2df7628ce34407b7',
    messagingSenderId: '1042384658326',
    projectId: 'mylatestproject-50982',
    databaseURL: 'https://mylatestproject-50982-default-rtdb.firebaseio.com',
    storageBucket: 'mylatestproject-50982.appspot.com',
    iosBundleId: 'com.example.violet.RunnerTests',
  );
}
